apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-svc
  name: db-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31111
  selector:
    app: db-pod
    #type: ClusterIP
  type: LoadBalancer
