apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-svc
  name: webapp-svc
spec:
  ports:
  - name: 31000-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: webapp
  type: LoadBalancer
status:
  loadBalancer: {}
